version: '3.4'

services:
  main:
    image: rummy-docker
    ports:
      - "9000:9000"
    command: (cd ~/htwg-rummy-game/rummy-main-service/src/main/scala/rummy) && sbt run
  game:
    image: rummy-docker
    ports:
      - "9001:9001"
    command: (cd ~/htwg-rummy-game/rummy-game-service/src/main/scala/game) && sbt run
  player:
    image: rummy-docker
    ports:
      - "9002:9002"
    command: (cd ~/htwg-rummy-game/rummy-player-service/src/main/scala/player) && sbt run