version: '3.4'
services:
  main:
    image: rummy-docker
    ports:
      - 9000:9000
    command: bash -c "cd ~/htwg-rummy-game/rummy-main-service && sbt run"
    networks:
      default:
        aliases:
          - main
    stdin_open:
      true
  game:
    image: rummy-docker
    ports:
      - 9001:9001
    networks:
      default:
        aliases:
          - game
    command: bash -c "cd ~/htwg-rummy-game/rummy-game-service && sbt run"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    command: --serviceExecutor adaptive
    networks:
      default:
        aliases:
          - mongo
#  player:
#    image: rummy-docker
#    ports:
#      - 9002:9002
#    networks:
#      default:
#        aliases:
#          - player
#    command: bash -c "cd ~/htwg-rummy-game/rummy-player-service && sbt run"